// بيانات أولية للمنتجات — تظهر في أول تشغيل، وتقدر تعدّلها من لوحة التحكم
export const CATEGORIES = [
  'فرامل',
  'فلاتر وصيانة',
  'عفشة وتعليق',
  'كهرباء وإشعال',
  'تبريد',
  'وقود',
  'هيكل وإكسسوارات',
];

export const SEED_PRODUCTS = [
  {
    id: 'p1', sku: 'BP-34116850568', name: 'طقم تيل فرامل أمامي Brembo', nameEn: 'Brembo Front Brake Pads Set',
    brand: 'BMW', models: ['F30', 'F10', 'F32'], category: 'فرامل', condition: 'new',
    price: 3400, oldPrice: 3900, wholesalePrice: 139, customsPct: 40, lengthCm: 30, widthCm: 20, heightCm: 10, weightKg: 4, cbm: 0.006, stock: 8, oem: '34116850568', image: '',
    description: 'طقم تيل فرامل أمامي بريمبو أصلي، مناسب لموديلات F30 و F10 و F32. صناعة إيطالية بضمان سنة.',
    descriptionEn: 'Genuine Brembo front brake pads set for F30, F10 and F32. Made in Italy with a one-year warranty.',
  },
  {
    id: 'p2', sku: 'BP-34216790966', name: 'تيل فرامل خلفي أصلي', nameEn: 'Genuine Rear Brake Pads',
    brand: 'BMW', models: ['E90', 'E92'], category: 'فرامل', condition: 'new',
    price: 2100, oldPrice: 0, wholesalePrice: 86, customsPct: 40, lengthCm: 30, widthCm: 20, heightCm: 10, weightKg: 4, cbm: 0.006, stock: 12, oem: '34216790966', image: '',
    description: 'تيل فرامل خلفي أصلي BMW لموديلات E90 و E92، وارد ألمانيا.',
    descriptionEn: 'Genuine BMW rear brake pads for E90 and E92, imported from Germany.',
  },
  {
    id: 'p3', sku: 'BP-34116794429', name: 'هوبات فرامل أمامية (طقم)', nameEn: 'Front Brake Discs (Set)',
    brand: 'BMW', models: ['F10', 'F11'], category: 'فرامل', condition: 'new',
    price: 5200, oldPrice: 5800, wholesalePrice: 212, customsPct: 40, lengthCm: 30, widthCm: 20, heightCm: 10, weightKg: 4, cbm: 0.006, stock: 4, oem: '34116794429', image: '',
    description: 'طقم أقراص (هوبات) فرامل أمامية مقاس 348مم لموديلات F10 و F11.',
    descriptionEn: '348mm front brake disc set for F10 and F11 models.',
  },
  {
    id: 'p4', sku: 'FL-HU6004X', name: 'فلتر زيت محرك MANN', nameEn: 'MANN Engine Oil Filter',
    brand: 'BMW', models: ['F30', 'F10', 'X1'], category: 'فلاتر وصيانة', condition: 'new',
    price: 450, oldPrice: 0, wholesalePrice: 18, customsPct: 40, lengthCm: 22, widthCm: 22, heightCm: 20, weightKg: 1.2, cbm: 0.0097, stock: 30, oem: '11428583898', image: '',
    description: 'فلتر زيت MANN الألماني لمحركات N20 و N26 و B48. الأعلى جودة في فئته.',
    descriptionEn: 'German MANN oil filter for N20, N26 and B48 engines. Best quality in its class.',
  },
  {
    id: 'p5', sku: 'FL-13718577171', name: 'فلتر هواء محرك B48/B58', nameEn: 'Engine Air Filter B48/B58',
    brand: 'BMW', models: ['G20', 'G30', 'X3'], category: 'فلاتر وصيانة', condition: 'new',
    price: 750, oldPrice: 0, wholesalePrice: 31, customsPct: 40, lengthCm: 22, widthCm: 22, heightCm: 20, weightKg: 1.2, cbm: 0.0097, stock: 20, oem: '13718577171', image: '',
    description: 'فلتر هواء أصلي لمحركات B48 و B58، مناسب للفئات G20 و G30 و X3 الجديدة.',
    descriptionEn: 'Genuine air filter for B48 and B58 engines — fits G20, G30 and new X3.',
  },
  {
    id: 'p6', sku: 'CO-11517586925', name: 'طلمبة مياه كهربائية', nameEn: 'Electric Water Pump',
    brand: 'BMW', models: ['E90', 'E60', 'X3'], category: 'تبريد', condition: 'used',
    price: 4800, oldPrice: 0, wholesalePrice: 196, customsPct: 40, lengthCm: 72, widthCm: 52, heightCm: 16, weightKg: 11, cbm: 0.0599, stock: 3, oem: '11517586925', image: '',
    description: 'طلمبة مياه كهربائية لمحرك N52، مستعمل وارد أوروبا بحالة ممتازة، مفحوصة بالكامل.',
    descriptionEn: 'Electric water pump for N52 engine. Used import from Europe, excellent condition, fully tested.',
  },
  {
    id: 'p7', sku: 'SU-31316873765', name: 'مساعدين أمامي (زوج)', nameEn: 'Front Shock Absorbers (Pair)',
    brand: 'BMW', models: ['F30', 'F31'], category: 'عفشة وتعليق', condition: 'used',
    price: 6500, oldPrice: 0, wholesalePrice: 265, customsPct: 40, lengthCm: 85, widthCm: 32, heightCm: 22, weightKg: 16, cbm: 0.0598, stock: 2, oem: '31316873765', image: '',
    description: 'زوج مساعدين أمامي أصلي فبريكا، مستعمل وارد ألمانيا، حالة ممتازة بدون تهريب.',
    descriptionEn: 'Pair of genuine OEM front shocks. Used import from Germany, excellent condition, no leaks.',
  },
  {
    id: 'p8', sku: 'SU-E46-ARM', name: 'مقصات أمامية كاملة بالجلد', nameEn: 'Complete Front Control Arms Kit',
    brand: 'BMW', models: ['E46'], category: 'عفشة وتعليق', condition: 'used',
    price: 3800, oldPrice: 0, wholesalePrice: 155, customsPct: 40, lengthCm: 85, widthCm: 32, heightCm: 22, weightKg: 16, cbm: 0.0598, stock: 5, oem: '31126757623', image: '',
    description: 'طقم مقصات أمامية كامل للـ E46 بالجلد والبيضات، مستعمل وارد بحالة الزيرو.',
    descriptionEn: 'Complete E46 front control arm kit with bushings and ball joints. Used import, like-new condition.',
  },
  {
    id: 'p9', sku: 'AC-64529399060', name: 'كمبروسر تكييف Denso', nameEn: 'Denso A/C Compressor',
    brand: 'BMW', models: ['F10', 'F30'], category: 'تبريد', condition: 'used',
    price: 9500, oldPrice: 11000, wholesalePrice: 388, customsPct: 40, lengthCm: 72, widthCm: 52, heightCm: 16, weightKg: 11, cbm: 0.0599, stock: 2, oem: '64529399060', image: '',
    description: 'كمبروسر تكييف دينسو مستعمل وارد، مفحوص على جهاز الشحن ويعمل بكفاءة 100%.',
    descriptionEn: 'Denso A/C compressor, used import. Bench-tested and working at 100% efficiency.',
  },
  {
    id: 'p10', sku: 'EL-R56-ALT', name: 'دينامو (مولد كهرباء)', nameEn: 'Alternator',
    brand: 'MINI', models: ['R56', 'R55'], category: 'كهرباء وإشعال', condition: 'used',
    price: 4200, oldPrice: 0, wholesalePrice: 171, customsPct: 40, lengthCm: 32, widthCm: 26, heightCm: 20, weightKg: 5, cbm: 0.0166, stock: 3, oem: '12317576514', image: '',
    description: 'دينامو ميني كوبر R56 مستعمل وارد أوروبا، مفحوص ومضمون شهر.',
    descriptionEn: 'MINI Cooper R56 alternator. Used import from Europe, tested with one-month warranty.',
  },
  {
    id: 'p11', sku: 'EL-F56-START', name: 'مارش (سلف) جديد', nameEn: 'Starter Motor (New)',
    brand: 'MINI', models: ['F56', 'F55'], category: 'كهرباء وإشعال', condition: 'new',
    price: 5600, oldPrice: 0, wholesalePrice: 228, customsPct: 40, lengthCm: 32, widthCm: 26, heightCm: 20, weightKg: 5, cbm: 0.0166, stock: 4, oem: '12418645324', image: '',
    description: 'مارش جديد لميني كوبر F55 و F56، صناعة Valeo بضمان سنة.',
    descriptionEn: 'New starter motor for MINI F55 and F56 by Valeo, one-year warranty.',
  },
  {
    id: 'p12', sku: 'EL-0258017025', name: 'حساس أكسجين Bosch', nameEn: 'Bosch Oxygen Sensor',
    brand: 'BMW', models: ['E90', 'E92', 'E60'], category: 'كهرباء وإشعال', condition: 'new',
    price: 2900, oldPrice: 3300, wholesalePrice: 118, customsPct: 40, lengthCm: 32, widthCm: 26, heightCm: 20, weightKg: 5, cbm: 0.0166, stock: 10, oem: '11787558073', image: '',
    description: 'حساس أكسجين (لامدا) بوش أصلي، قبل الكتليزر، لمحركات N52 و N53.',
    descriptionEn: 'Genuine Bosch lambda (O2) sensor, pre-cat, for N52 and N53 engines.',
  },
  {
    id: 'p13', sku: 'IG-NGK-B58', name: 'طقم بوجيهات NGK (6 قطع)', nameEn: 'NGK Spark Plugs Set (6 pcs)',
    brand: 'BMW', models: ['G20', 'G30', 'X5'], category: 'كهرباء وإشعال', condition: 'new',
    price: 3600, oldPrice: 0, wholesalePrice: 147, customsPct: 40, lengthCm: 32, widthCm: 26, heightCm: 20, weightKg: 5, cbm: 0.0166, stock: 15, oem: '12120040551', image: '',
    description: 'طقم 6 بوجيهات NGK ليزر بلاتينيوم لمحرك B58، الأصلية من مصنع BMW.',
    descriptionEn: 'Set of 6 NGK Laser Platinum spark plugs for the B58 engine — BMW factory original.',
  },
  {
    id: 'p14', sku: 'IG-12138616153', name: 'طقم كويلات إشعال (6 قطع)', nameEn: 'Ignition Coils Set (6 pcs)',
    brand: 'BMW', models: ['F30', 'F10', 'X6'], category: 'كهرباء وإشعال', condition: 'new',
    price: 7200, oldPrice: 8000, wholesalePrice: 294, customsPct: 40, lengthCm: 32, widthCm: 26, heightCm: 20, weightKg: 5, cbm: 0.0166, stock: 6, oem: '12138616153', image: '',
    description: 'طقم كويلات Delphi لمحرك N55، بديل أصلي بضمان سنة كاملة.',
    descriptionEn: 'Delphi ignition coil set for the N55 engine. OEM replacement with full one-year warranty.',
  },
  {
    id: 'p15', sku: 'BD-F30-MIRROR', name: 'غطاء مراية كربون (زوج)', nameEn: 'Carbon Mirror Caps (Pair)',
    brand: 'BMW', models: ['F30', 'F32', 'F36'], category: 'هيكل وإكسسوارات', condition: 'new',
    price: 2500, oldPrice: 0, wholesalePrice: 102, customsPct: 40, lengthCm: 62, widthCm: 42, heightCm: 30, weightKg: 6, cbm: 0.0781, stock: 7, oem: '', image: '',
    description: 'زوج غطاء مرايات كربون فايبر حقيقي لموديلات F30 و F32، تركيب مباشر بدون تعديل.',
    descriptionEn: 'Pair of real carbon fibre mirror caps for F30 and F32 — direct fit, no modification needed.',
  },
  {
    id: 'p16', sku: 'BD-51138072085', name: 'شبكة أمامية (كلاوي) G20', nameEn: 'Front Kidney Grille G20',
    brand: 'BMW', models: ['G20'], category: 'هيكل وإكسسوارات', condition: 'new',
    price: 4800, oldPrice: 0, wholesalePrice: 196, customsPct: 40, lengthCm: 62, widthCm: 42, heightCm: 30, weightKg: 6, cbm: 0.0781, stock: 5, oem: '51138072085', image: '',
    description: 'كلاوي أسود لامع (Shadow Line) للفئة الثالثة G20، خامة أصلية.',
    descriptionEn: 'Gloss black Shadow Line kidney grille for the 3 Series G20, genuine quality.',
  },
  {
    id: 'p17', sku: 'LT-F30-LCI', name: 'فانوس أمامي LED يمين', nameEn: 'LED Headlight Right F30 LCI',
    brand: 'BMW', models: ['F30'], category: 'هيكل وإكسسوارات', condition: 'used',
    price: 14500, oldPrice: 0, wholesalePrice: 591, customsPct: 40, lengthCm: 62, widthCm: 42, heightCm: 30, weightKg: 6, cbm: 0.0781, stock: 1, oem: '63117419634', image: '',
    description: 'فانوس أمامي LED أصلي للـ F30 LCI (الشكل الجديد)، مستعمل وارد بحالة ممتازة بدون كسور.',
    descriptionEn: 'Genuine LED headlight for F30 LCI (facelift). Used import, excellent condition, no cracks.',
  },
  {
    id: 'p18', sku: 'CO-17117600511', name: 'ردياتير مياه أصلي', nameEn: 'Genuine Radiator',
    brand: 'BMW', models: ['F30', 'F20', 'F22'], category: 'تبريد', condition: 'new',
    price: 6800, oldPrice: 7500, wholesalePrice: 277, customsPct: 40, lengthCm: 72, widthCm: 52, heightCm: 16, weightKg: 11, cbm: 0.0599, stock: 4, oem: '17117600511', image: '',
    description: 'ردياتير مياه أصلي لموديلات F20 و F22 و F30، وارد ألمانيا بالكرتونة.',
    descriptionEn: 'Genuine coolant radiator for F20, F22 and F30 — imported from Germany, boxed.',
  },
  {
    id: 'p19', sku: 'FU-R56-PUMP', name: 'طرمبة بنزين كاملة', nameEn: 'Complete Fuel Pump',
    brand: 'MINI', models: ['R56', 'R57'], category: 'وقود', condition: 'used',
    price: 3200, oldPrice: 0, wholesalePrice: 131, customsPct: 40, lengthCm: 30, widthCm: 26, heightCm: 26, weightKg: 4, cbm: 0.0203, stock: 3, oem: '16112755082', image: '',
    description: 'طرمبة بنزين كاملة بالعوامة لميني كوبر R56، مستعمل وارد مفحوص.',
    descriptionEn: 'Complete fuel pump with sender unit for MINI R56. Used import, tested.',
  },
  {
    id: 'p20', sku: 'SU-X5-REAR', name: 'عفشة خلفية كاملة X5', nameEn: 'Complete Rear Suspension X5',
    brand: 'BMW', models: ['X5'], category: 'عفشة وتعليق', condition: 'used',
    price: 18500, oldPrice: 0, wholesalePrice: 755, customsPct: 40, lengthCm: 85, widthCm: 32, heightCm: 22, weightKg: 16, cbm: 0.0598, stock: 1, oem: '', image: '',
    description: 'عفشة خلفية كاملة (مقصات + مساعدين + أكصات) للـ X5 E70، وارد أمريكا بحالة ممتازة.',
    descriptionEn: 'Complete rear suspension (arms, shocks, axles) for X5 E70. US import, excellent condition.',
  },
  {
    id: 'p21', sku: 'FC-F30-2014-BLK', name: 'نص كت أمامي كامل F30 أسود 2014', nameEn: 'Complete Front Cut (Front End) F30 Black 2014',
    brand: 'BMW', models: ['F30'], category: 'هيكل وإكسسوارات', condition: 'used',
    price: 34500, oldPrice: 0, wholesalePrice: 2500, customsPct: 40, lengthCm: 150, widthCm: 90, heightCm: 80, weightKg: 110, cbm: 1.08, stock: 1, oem: '', image: '',
    description: 'نص كت أمامي كامل لـ BMW F30 موديل 2014، لون أسود — مستعمل وارد بحالة ممتازة. المكوّنات: طقم فوانيس زينون (Xenon) + اكصدام أمامي كامل + صدر كامل (وش) + طقم تبريد كامل (رديتر + مراوح).',
    descriptionEn: 'Complete front cut (front end) for BMW F30, 2014, black — used import, excellent condition. Includes: Xenon headlights set + complete front bumper + complete front panel + full cooling pack (radiator + fans).',
  },
];

// 🧩 حاوية تجريبية للمشاركة — تظهر في أول تشغيل، وتقدر تحذفها/تعدّلها من لوحة التحكم
export const SEED_CONTAINERS = [
  {
    id: 'sh-demo-1',
    ref: 'CNT-SHJ001',
    laneCode: 'EG',
    port: 'الإسكندرية',
    containerCode: '40HC',
    containerName: 'حاوية 40 قدم عالية',
    capacityCbm: 68,
    bookedCbm: 42,
    baseFreightUsd: 2500,
    status: 'filling',
    cutoffDate: '2026-09-10',
    etd: '2026-09-15',
    createdAt: new Date().toISOString(),
    bookings: [
      { id: 'bk-d1', name: 'محمد فتحي', company: 'قطع غيار النصر', country: 'مصر', phone: '201001234567', cbm: 20, shareUsd: 735.29, status: 'reserved', at: new Date().toISOString() },
      { id: 'bk-d2', name: 'Ivan Petrov', company: 'Ivan Auto', country: 'روسيا', phone: '79161234567', cbm: 14, shareUsd: 514.71, status: 'reserved', at: new Date().toISOString() },
      { id: 'bk-d3', name: 'أحمد سالم', company: 'ورشة الخليج', country: 'مصر', phone: '201112223334', cbm: 8, shareUsd: 294.12, status: 'reserved', at: new Date().toISOString() },
    ],
  },
];
